// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nuka.Sample.API.Data;

namespace Nuka.Sample.API.Migrations.Sample
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20210107043543_UpdateSampleMigrations")]
    partial class UpdateSampleMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Nuka.Sample.API.Data.Entities.SampleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FID")
                        .UseIdentityColumn();

                    b.Property<Guid>("CacheIndex")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FCACHEINDEX");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FCREATEDTIME");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FCREATEDUSER");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FDISCIPTION");

                    b.Property<string>("ItemId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FITEMID");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FITEMNAME");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FUPDATEDTIME");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FUPDATEDUSER");

                    b.Property<string>("LastUpdatedFunc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FUPDATEDFUNCTION");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("FPRICE");

                    b.Property<int>("SampleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FTYPEID");

                    b.HasKey("Id");

                    b.HasIndex("SampleTypeId");

                    b.ToTable("ITEMM");
                });

            modelBuilder.Entity("Nuka.Sample.API.Data.Entities.SampleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FID")
                        .UseIdentityColumn();

                    b.Property<Guid>("CacheIndex")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FCACHEINDEX");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FCREATEDTIME");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FCREATEDUSER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FUPDATEDTIME");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FUPDATEDUSER");

                    b.Property<string>("LastUpdatedFunc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FUPDATEDFUNCTION");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FTYPE");

                    b.HasKey("Id");

                    b.ToTable("TYPEM");
                });

            modelBuilder.Entity("Nuka.Sample.API.Data.Entities.SampleItem", b =>
                {
                    b.HasOne("Nuka.Sample.API.Data.Entities.SampleType", "SampleType")
                        .WithMany()
                        .HasForeignKey("SampleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SampleType");
                });
#pragma warning restore 612, 618
        }
    }
}
