### GET ACCESS TOKEN
POST https://localhost:5000/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=sample.api.access&client_id=test_client&client_secret=test_secret

### Test Service
GET http://localhost:5001/Home/Index
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJERDM3MUIyODJDQkQ3MzEwQUQ3MTk2OUMzMEUyRUNDQkQ2OENDRjNSUzI1NiIsInR5cCI6ImF0K2p3dCIsIng1dCI6InZkTnhzb0xMMXpFSzF4bHB3dzR1ekwxb3pQTSJ9.eyJuYmYiOjE2MTQ3NTg0OTIsImV4cCI6MTYxNDg0NDg5MiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMCIsImF1ZCI6InNhbXBsZS5hcGkiLCJjbGllbnRfaWQiOiJ0ZXN0X2NsaWVudCIsImp0aSI6IkEwNzY5OTY5QjQxMzNCMjE2NjA4OTI0NUQ0NTJBQzQzIiwiaWF0IjoxNjE0NzU4NDkyLCJzY29wZSI6WyJzYW1wbGUuYXBpLmFjY2VzcyJdfQ.HpC54jpxKZ-3UilfgFepaWBbHVHHm9mAYRtV5pEV6XNL6nbarY7-pIxWKvM9w9mQlC6OhysfI3KCDi3Drkwawnz9CWy5N5aW_b3hmkmTkh0N1vC7MZlZpXxZyI0pc7j3YtoyZYCe_K13PBCUdaz4gqBPB6ovIsJZwzwzuAO46y-AQint-dNBkzlL1qT-WHwlV1l_aiNIX8cHh_Q9cK7lR65Ecz93qREJYgWvM4_oAyv0we9m0Q9ibMO7__6oWzQn3xjNM5979sllsoxGTQbreZlXl4niKSjYqe-XPjcTd2iJTzSEvh8iKh2Y49W6ku4VCbNGt19hYlyL-j4qJkAcMA


### Test in Gateway
GET http://localhost:5200/sample/Home/Index

### Liveness
http://localhost:5001/.internal/live

### Readiness
http://localhost:5001/.internal/ready

### Health Info
http://localhost:5001/.internal/hc

### Self Info
http://localhost:5001/.internal/self

### Error
http://localhost:5001/Home/Error