### GET ACCESS TOKEN
POST https://localhost:5000/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=sample.api.access&client_id=test_client&client_secret=test_secret

### Test Service
GET http://localhost:5001/Home/Index
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkJERDM3MUIyODJDQkQ3MzEwQUQ3MTk2OUMzMEUyRUNDQkQ2OENDRjNSUzI1NiIsInR5cCI6ImF0K2p3dCIsIng1dCI6InZkTnhzb0xMMXpFSzF4bHB3dzR1ekwxb3pQTSJ9.eyJuYmYiOjE2MTM5OTcyNzIsImV4cCI6MTYxNDA4MzY3MiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMCIsImF1ZCI6InNhbXBsZS5hcGkiLCJjbGllbnRfaWQiOiJ0ZXN0X2NsaWVudCIsImp0aSI6IkI2REY4MjFGNTA2OTg0QkRCRDhDRUU1OEQyRTc4MEQ2IiwiaWF0IjoxNjEzOTk3MjcyLCJzY29wZSI6WyJzYW1wbGUuYXBpLmFjY2VzcyJdfQ.SVAtd9GpHgrckGvYAup154bjK9dJHt-m1dHOfHrWWWMdzIy2v14qWeTj9KMQGhxC5RG4mh9j8glvaVeCyplWe5yAHlKhlBC-4XxtXZhurQdvfJ2i-5BV7E4yR6gMIjUQujsqhM1KhFsXupbNL_2M4r1nhzRNonZcfvjGNuHyLzrcAm_TEhSiA_9SOiFzC-aRkjkyGlKSusn4oqAt33XQ-m1KpPj31aBe2tDX3UDHA346LmxZxmLQH12DNfHMzRj5dz7Jhz7vKcO6h3sxaQBXcnxfgEoziC7-mfws5r469mlS7xaahw3Djftjl9PnNBOGiIOqLvb_iVH3LdKNneSBeg


### Test in Gateway
GET http://localhost:5200/sample/Home/Index