version: '3.4'

services:
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    networks: 
      - nuka-network

  sample-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP_PORT=80
      - GRPC_PORT=81
      - ConnectionStrings__DefaultConnection=Server=sqldata;Database=Nuka.Sample.API;User Id=sa;Password=Pass@word
    ports:
      - "5001:80"
      - "9001:81"
    networks:
      - nuka-network
  
networks:
  nuka-network:
    external: true