version: '3.4'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.10.1
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      discovery.type: single-node
    networks:
    - network
  kibana:
    container_name: kibana
    image: kibana:7.10.1
    depends_on:
    - elasticsearch
    ports:
    - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
    - network
  fluentd:
    container_name: fluentd
    image: zhuxiang1212/efk-fluentd:7.10.1
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
    - elasticsearch
    ports:
    - "9880:9880"
    environment:
      FLUENTD_CONF: fluentd.conf
    volumes:
    - $PWD:/fluentd/etc
    networks:
    - network
networks:
  network:
    driver: bridge
